[metadata]
icon = "mdi:presentation"
name = "MkReprRawRendered"
group = "documentation"
virtual_children = true

[examples.regular]
title = "Regular"
jinja = """
{{ "Some text" | MkAdmonition | MkReprRawRendered }}
"""

[output.markdown]
template = """
{% if node.node %}
{% set html_node = node.node.__copy__(as_html=True) %}
{{ node.node | repr | MkCode | MkTab(title="Repr", new=True) }}
{{ node.node | MkCode(language="markdown") | MkTab(title="Raw") }}
{{ html_node | MkCode(language="html") | MkTab(title="Html") }}
{{ node.node | MkTab(title="Rendered", select=True) }}
{% if node.node.children %}
{{ node.node | MkTreeView | MkTab(title="Repr tree") }}{% endif %}{% endif %}
"""
