[metadata]
icon = "octicon:info-16"
name = "MkAdmonitionBlock"

[requirements.extension."pymdownx.blocks.admonition"]


[examples."Default"]
jinja = """
{{ "Different types." | MkAdmonitionBlock(typ="warning") | MkReprRawRendered }}
"""

[output.markdown]
template = """
{{ node.fence_boundary }} admonition{% if node.argument %}" | " ~ {{ node.argument }}{% endif %}

    type: {{ node.typ }}
{{ node.items | join }}

{{ node.fence_boundary }}

"""
