[metadata]
name = "MkMaterialBadge"
icon = "simple-icons:shieldsdotio"

[[resources.css]]
filename = "materialbadge.css"

[examples."Regular"]
jinja = """
{{ "mdi:wrench" | MkMaterialBadge(text="text") | MkReprRawRendered }}
"""

[examples."Heart type"]
jinja = """
{{ "mdi:file" | MkMaterialBadge(text="text", typ="heart") | MkReprRawRendered }}
"""

[examples."Right aligned"]
jinja = """
{{ "mdi:file" | MkMaterialBadge(text="text", typ="right") | MkReprRawRendered }}
"""

[output]
xml = """
<span class="md-typeset mdx-badge{{ " mdx-badge--right" if right_aligned else "" }}{{ " mdx-badge--heart" if animated else "" }}">
  {% if icon %}<span class="mdx-badge__icon">{{ icon }}</span>{% endif %}
  {% if text %}<span class="mdx-badge__text">{{ text }}</span>{% endif %}
</span>
"""
