[filters.get_link]
fn = "mknodes.jinja.filters.get_link"
group = "node"

[filters.get_link.examples.class]
template = """
{{ _mk.MkAdmonition | get_link }}
"""


[filters.get_url]
fn = "mknodes.jinja.filters.get_url"
group = "node"

[filters.get_url.examples.class]
template = """
{{ _mk.MkAdmonition | get_url }}
"""


[filters.link_for_class]
fn = "mknodes.jinja.filters.link_for_class"
group = "node"

[filters.link_for_class.examples.class]
template = """
{{ _mk.MkAdmonition | link_for_class }}
"""


[filters.link_for_module]
fn = "mknodes.jinja.filters.link_for_module"
group = "node"


[filters.to_html]
fn = "mknodes.jinja.filters.to_html"
group = "node"

[filters.to_html.examples.class]
template = """
{{ "test" | MkAdmonition | to_html }}
"""


[filters.apply_mod]
fn = "mknodes.jinja.filters.apply_mod"
group = "node"

[filters.apply_mod.examples.class]
template = """
{{ "test" | MkAdmonition | apply_mod("ParallaxEffect") }}
"""
